// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG8YEVkY9KsQzcASmYEFnIleC-zg__G4U',
    appId: '1:718044139435:web:23e15100e68c76117d8cee',
    messagingSenderId: '718044139435',
    projectId: 'quickdrop-19299',
    authDomain: 'quickdrop-19299.firebaseapp.com',
    storageBucket: 'quickdrop-19299.appspot.com',
    measurementId: 'G-E664DZY93N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoiBfXzTMi-VoWnWBrwlvGEcW_KjgW37I',
    appId: '1:718044139435:android:dd102c60d175ffb67d8cee',
    messagingSenderId: '718044139435',
    projectId: 'quickdrop-19299',
    storageBucket: 'quickdrop-19299.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSYFBzrHav3xK_ol4W-93DV2-EDS9iEA8',
    appId: '1:718044139435:ios:fda00e9e5b5ad7c47d8cee',
    messagingSenderId: '718044139435',
    projectId: 'quickdrop-19299',
    storageBucket: 'quickdrop-19299.appspot.com',
    iosClientId: '718044139435-giovir8fb31e2k1ld2bbqfpjbja4sr69.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickDrop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSYFBzrHav3xK_ol4W-93DV2-EDS9iEA8',
    appId: '1:718044139435:ios:9a30a605332109387d8cee',
    messagingSenderId: '718044139435',
    projectId: 'quickdrop-19299',
    storageBucket: 'quickdrop-19299.appspot.com',
    iosClientId: '718044139435-ddet429bulaivr7thnesk8tagcaktcde.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickDrop.RunnerTests',
  );
}
